name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{env.PROJECT_ID}}
          service_account_key: ${{ secrets.GCP_SA }}
          export_default_credentials: true

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: upload-file
          runtime: go121
          project_id: ${{ secrets.PROJECT_ID }}
          source_dir: "./uploadFile"
          entry_point: functions.UploadFiletoStorageBucket

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"

