name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
    paths:
      - uploadFile
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{env.PROJECT_ID}}
          credentials_json: '${{ secrets.GCP_SA }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: upload-file
          runtime: go121
          project_id: ${{ secrets.PROJECT_ID }}
          source_dir: "./uploadFile"
          entry_point: UploadFiletoStorageBucket

      - name: Test the url
        run: curl "${{ steps.deploy.outputs.url }}"

